port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
  - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - 8.8.8.8   # Google DNS over TCP
  - 1.1.1.1   # cloudflare DNS over TCP
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4
# 个人节点
proxies:
- name: 🇨🇳:中国-ss-zh01lv5au05.feiguayun.xyz:39087-可用-中转:194.195.122.155-仅支持澳大利亚地区NF自制剧
  type: ss
  server: zh01lv5au05.feiguayun.xyz
  password: 4b5d7ed5-e1a3-4947-b955-58a39a29cc29
  port: 39087
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-zh01lv5ca03.feiguayun.xyz:37087-可用-中转:172.105.17.53-仅支持加拿大地区NF自制剧
  type: ss
  server: zh01lv5ca03.feiguayun.xyz
  password: 4b5d7ed5-e1a3-4947-b955-58a39a29cc29
  port: 37087
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-85.208.108.20:7002-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  type: ss
  server: 85.208.108.20
  password: RexnBgU7EV5ADxG
  port: 7002
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-zh01lv5uk04.feiguayun.xyz:35087-可用-中转:176.58.101.189-仅支持英国地区NF自制剧
  type: ss
  server: zh01lv5uk04.feiguayun.xyz
  password: 4b5d7ed5-e1a3-4947-b955-58a39a29cc29
  port: 35087
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.121.43.65:2375-可用-直连-仅支持美国地区NF自制剧
  type: ss
  server: 38.121.43.65
  password: faBAoD54k87UJG7
  port: 2375
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-85.208.108.20:6697-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  type: ss
  server: 85.208.108.20
  password: TEzjfAYq2IjtuoS
  port: 6697
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-zh01lv5sgp03.feiguayun.xyz:34087-可用-中转:45.118.132.179-仅支持新加坡地区NF自制剧
  type: ss
  server: zh01lv5sgp03.feiguayun.xyz
  password: 4b5d7ed5-e1a3-4947-b955-58a39a29cc29
  port: 34087
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-85.208.108.20:6679-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  type: ss
  server: 85.208.108.20
  password: TEzjfAYq2IjtuoS
  port: 6679
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-zh01lv3uk01.feiguayun.xyz:50011-可用-中转:176.58.126.232-仅支持英国地区NF自制剧
  type: ss
  server: zh01lv3uk01.feiguayun.xyz
  password: efafd384-706a-4539-a169-5726c3d51516
  port: 50011
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-zh01lv5sgp01.feiguayun.xyz:34087-可用-中转:45.118.132.179-仅支持新加坡地区NF自制剧
  type: ss
  server: zh01lv5sgp01.feiguayun.xyz
  password: efafd384-706a-4539-a169-5726c3d51516
  port: 34087
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-45.66.134.176:807-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 807
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:806-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 806
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:805-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:805-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:801-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 801
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:812-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:809-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 809
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-89.31.126.171:800-被墙-中转:5.181.5.184-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.171
  password: G!yBwPWH3Vao
  port: 800
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-138.68.248.130:811-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 138.68.248.130
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.168:25218-可用-直连-完全不支持NF
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25218
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11038-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11038
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-180.163.62.91:10064-可用-中转:129.227.4.80-不支持Netflix
  type: ss
  server: 180.163.62.91
  password: QazEdcTgb159@$*
  port: 10064
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25220-可用-直连-完全不支持NF
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25220
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25217-可用-直连-完全不支持NF
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25217
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11050-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11050
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25222-可用-直连-完全不支持NF
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25222
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25247-可用-直连-完全不支持NF
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25247
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:24026-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 24026
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11005-可用-中转:129.227.144.194-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11005
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11041-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11041
  cipher: aes-128-cfb
- name: 🇩🇪:德国-ss-165.22.73.126:23335-可用-直连-仅支持德国地区NF自制剧
  type: ss
  server: 165.22.73.126
  password: 7d99ae502227454ea998d71e4b62a388
  port: 23335
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:24000-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 24000
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-180.163.62.91:10065-可用-中转:129.227.4.81-不支持Netflix
  type: ss
  server: 180.163.62.91
  password: QazEdcTgb159@$*
  port: 10065
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11043-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11043
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:24046-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 24046
  cipher: aes-128-cfb
- name: 🇯🇵:日本-ss-45.66.134.176:810-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 810
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:801-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 801
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:802-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  type: ss
  server: 213.169.137.221
  password: f8f7aCzcPKbsF8p3
  port: 989
  cipher: aes-256-cfb
- name: 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 31.133.100.49
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 83.229.73.60
  password: '8460400130'
  port: 50003
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.126.217
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.125.91
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-gy.ziqiyun.xyz:44041-被墙-中转:138.2.54.183-解锁日本地区NF非自制剧
  type: ss
  server: gy.ziqiyun.xyz
  password: 297545c2-a59d-4610-9580-a7baa3657a57
  port: 44041
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-vmess-ifffffffuuuuuuus.qiqicdn2.cf:443-可用-中转:34.229.179.34-解锁美国地区NF非自制剧
  type: vmess
  server: ifffffffuuuuuuus.qiqicdn2.cf
  network: ws
  port: 443
  uuid: 5a36cce4-0527-4d36-bf4a-6c215ef9c524
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /5a36cce4-0527-4d36-bf4a-6c215ef9c524-vmess
- name: 🇺🇸:美国-vmess-sg01.czsx1624.tk:443-可用-中转:138.2.88.131-解锁新加坡地区NF非自制剧
  type: vmess
  server: sg01.czsx1624.tk
  network: ws
  port: 443
  uuid: d002b422-eace-4e01-bf58-e4bb0bcfe7af
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /3a8545177/
- name: 🇺🇸:美国-vmess-v1.ssrsub.com:8443-可用-中转:193.38.51.192-完全不支持NF
  type: vmess
  server: v1.ssrsub.com
  network: ws
  port: 8443
  uuid: 2256dea6-b952-43f7-b8a2-983f766d5836
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /api/v3/download.getFile

# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
proxy-groups:
  # 保留的自定义节点
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-v1.ssrsub.com:8443-可用-中转:193.38.51.192-完全不支持NF
  - 🇺🇸:美国-vmess-sg01.czsx1624.tk:443-可用-中转:138.2.88.131-解锁新加坡地区NF非自制剧
  - 🇺🇸:美国-vmess-ifffffffuuuuuuus.qiqicdn2.cf:443-可用-中转:34.229.179.34-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.121.43.65:2375-可用-直连-仅支持美国地区NF自制剧
  - 🇯🇵:日本-ss-85.208.108.20:7002-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  - 🇯🇵:日本-ss-85.208.108.20:6697-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  - 🇯🇵:日本-ss-85.208.108.20:6679-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  - 🇩🇪:德国-ss-165.22.73.126:23335-可用-直连-仅支持德国地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5uk04.feiguayun.xyz:35087-可用-中转:176.58.101.189-仅支持英国地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5sgp03.feiguayun.xyz:34087-可用-中转:45.118.132.179-仅支持新加坡地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5sgp01.feiguayun.xyz:34087-可用-中转:45.118.132.179-仅支持新加坡地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5ca03.feiguayun.xyz:37087-可用-中转:172.105.17.53-仅支持加拿大地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5au05.feiguayun.xyz:39087-可用-中转:194.195.122.155-仅支持澳大利亚地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv3uk01.feiguayun.xyz:50011-可用-中转:176.58.126.232-仅支持英国地区NF自制剧
  - 🇨🇳:中国-ss-180.163.62.91:10065-可用-中转:129.227.4.81-不支持Netflix
  - 🇨🇳:中国-ss-180.163.62.91:10064-可用-中转:129.227.4.80-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11050-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11043-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11041-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11038-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11005-可用-中转:129.227.144.194-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25247-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-14.29.124.168:25222-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-14.29.124.168:25220-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-14.29.124.168:25218-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-14.29.124.168:25217-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-14.29.124.168:24046-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24026-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24000-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
- name: 被墙代理组
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-ss-138.68.248.130:811-被墙-直连-解锁美国地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.171:800-被墙-中转:5.181.5.184-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:810-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:809-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:807-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:805-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:801-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  - 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  - 🇨🇳:中国-ss-gy.ziqiyun.xyz:44041-被墙-中转:138.2.54.183-解锁日本地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:812-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:806-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:805-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:802-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:801-被墙-直连-解锁加拿大地区NF非自制剧
- name: 仅支持Netflix自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-ss-38.121.43.65:2375-可用-直连-仅支持美国地区NF自制剧
  - 🇯🇵:日本-ss-85.208.108.20:7002-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  - 🇯🇵:日本-ss-85.208.108.20:6697-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  - 🇯🇵:日本-ss-85.208.108.20:6679-可用-中转:85.208.108.18-仅支持日本地区NF自制剧
  - 🇩🇪:德国-ss-165.22.73.126:23335-可用-直连-仅支持德国地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5uk04.feiguayun.xyz:35087-可用-中转:176.58.101.189-仅支持英国地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5sgp03.feiguayun.xyz:34087-可用-中转:45.118.132.179-仅支持新加坡地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5sgp01.feiguayun.xyz:34087-可用-中转:45.118.132.179-仅支持新加坡地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5ca03.feiguayun.xyz:37087-可用-中转:172.105.17.53-仅支持加拿大地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv5au05.feiguayun.xyz:39087-可用-中转:194.195.122.155-仅支持澳大利亚地区NF自制剧
  - 🇨🇳:中国-ss-zh01lv3uk01.feiguayun.xyz:50011-可用-中转:176.58.126.232-仅支持英国地区NF自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24046-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24026-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24000-可用-中转:223.26.73.202-仅支持台湾地区NF自制剧
- name: 解锁Netflix非自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-sg01.czsx1624.tk:443-可用-中转:138.2.88.131-解锁新加坡地区NF非自制剧
  - 🇺🇸:美国-vmess-ifffffffuuuuuuus.qiqicdn2.cf:443-可用-中转:34.229.179.34-解锁美国地区NF非自制剧
- name: 入口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
  - PROXY
- name: 出口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 被墙代理组
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
- name: RELAY_PROXY
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: relay
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 入口代理组
  - 出口代理组
- name: NETFLIX_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Tiktok_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Bili_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
- name: IQiyi_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY

# 黑名单模式，命中规则使用代理
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
  # > Netflix
- DOMAIN-SUFFIX,netflix.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflix.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxext.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxso.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxvideo.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest0.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest1.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest2.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest3.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest4.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest5.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest6.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest7.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest8.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest9.com,NETFLIX_PROXY
  # Netflix测速网站
- DOMAIN-SUFFIX,fast.com,NETFLIX_PROXY
  # - RULE-SET,video_netflix,NETFLIX_PROXY
  # > TikTok
- PROCESS-NAME,com.ss.android.ugc.trill,Tiktok_PROXY
- DOMAIN-SUFFIX,byteoversea.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ibytedtos.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ipstatp.com,Tiktok_PROXY
- DOMAIN-SUFFIX,muscdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,musical.ly,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktok.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tik-tokapi.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokcdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokv.com,Tiktok_PROXY
  # - RULE-SET,video_tiktok,Tiktok_PROXY
  # > iQIYI
- DOMAIN-SUFFIX,iq.com,IQiyi_PROXY
- DOMAIN,intl.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-rcd.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-subscription.iqiyi.com,IQiyi_PROXY
  # - RULE-SET,video_iqiyi,IQiyi_PROXY
  # > Bilibili
- PROCESS-NAME,com.bilibili.app.in,Bili_PROXY
- PROCESS-NAME,tv.danmaku.bili,Bili_PROXY
- DOMAIN-SUFFIX,acg.tv,Bili_PROXY
- DOMAIN-SUFFIX,acgvideo.com,Bili_PROXY
- DOMAIN-SUFFIX,b23.tv,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.com,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.net,Bili_PROXY
- DOMAIN-SUFFIX,bilibili.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.net,Bili_PROXY
- DOMAIN-SUFFIX,bilivideo.com,Bili_PROXY
- DOMAIN-SUFFIX,hdslb.com,Bili_PROXY
- DOMAIN-SUFFIX,im9.com,Bili_PROXY
- DOMAIN-SUFFIX,smtcdns.net,Bili_PROXY
  # 后面追加规则
