port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
  - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - 8.8.8.8   # Google DNS over TCP
  - 1.1.1.1   # cloudflare DNS over TCP
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4
# 个人节点
proxies:
- name: 🇺🇸:美国-ss-92.38.176.81:811-可用-直连-不支持Netflix
  type: ss
  server: 92.38.176.81
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.191:443-可用-直连-不支持Netflix
  type: ss
  server: 38.68.134.191
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-142.202.48.52:443-可用-直连-不支持Netflix
  type: ss
  server: 142.202.48.52
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.63.79:443-可用-直连-不支持Netflix
  type: ss
  server: 167.88.63.79
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-142.202.48.58:443-可用-直连-不支持Netflix
  type: ss
  server: 142.202.48.58
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-138.68.248.130:811-可用-直连-不支持Netflix
  type: ss
  server: 138.68.248.130
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.91.100.27:443-可用-直连-不支持Netflix
  type: ss
  server: 38.91.100.27
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.114.114.19:443-可用-直连-不支持Netflix
  type: ss
  server: 38.114.114.19
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-142.202.48.74:443-可用-直连-不支持Netflix
  type: ss
  server: 142.202.48.74
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-134.195.196.227:443-可用-直连-不支持Netflix
  type: ss
  server: 134.195.196.227
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-169.197.142.187:443-可用-直连-不支持Netflix
  type: ss
  server: 169.197.142.187
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.121.43.71:443-可用-直连-不支持Netflix
  type: ss
  server: 38.121.43.71
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.61.60:443-可用-直连-不支持Netflix
  type: ss
  server: 167.88.61.60
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.136.102:443-可用-直连-不支持Netflix
  type: ss
  server: 38.75.136.102
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-144.91.109.75:443-可用-直连-不支持Netflix
  type: ss
  server: 144.91.109.75
  password: revC4XzAemkX
  port: 443
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-38.64.138.145:443-可用-直连-不支持Netflix
  type: ss
  server: 38.64.138.145
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-142.202.48.99:443-可用-直连-不支持Netflix
  type: ss
  server: 142.202.48.99
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.114.114.67:443-可用-直连-不支持Netflix
  type: ss
  server: 38.114.114.67
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.61.175:443-可用-直连-不支持Netflix
  type: ss
  server: 167.88.61.175
  password: pKEW8JPByTVTLtM
  port: 443
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-45.66.134.176:807-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 807
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:806-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 806
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:805-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:805-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:801-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 801
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:803-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 803
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:812-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:809-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 809
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-89.31.126.171:800-被墙-中转:5.181.5.184-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.171
  password: G!yBwPWH3Vao
  port: 800
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.168:25252-可用-直连-完全不支持NF
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25252
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11033-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11033
  cipher: aes-128-cfb
- name: 🇷🇺:俄罗斯-ss-185.4.65.6:21247-可用-中转:37.252.1.212-完全不支持NF
  type: ss
  server: 185.4.65.6
  password: vDS9G2p
  port: 21247
  cipher: aes-256-cfb
- name: 🇷🇺:俄罗斯-ss-217.30.10.65:9008-可用-直连-仅支持波兰地区NF自制剧
  type: ss
  server: 217.30.10.65
  password: y9VURyNzJWNRYEGQ
  port: 9008
  cipher: aes-256-cfb
- name: 🇳🇱:荷兰-ss-213.183.51.171:9010-可用-直连-仅支持荷兰地区NF自制剧
  type: ss
  server: 213.183.51.171
  password: f63gg8EruDnUrmz4
  port: 9010
  cipher: aes-256-cfb
- name: 🇷🇺:俄罗斯-ss-213.183.53.208:9041-可用-直连-完全不支持NF
  type: ss
  server: 213.183.53.208
  password: U6qnYRhfyDmn8sgn
  port: 9041
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:24008-可用-中转:223.26.73.202-解锁台湾地区NF非自制剧
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 24008
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-180.163.62.91:10064-可用-中转:129.227.4.80-不支持Netflix
  type: ss
  server: 180.163.62.91
  password: QazEdcTgb159@$*
  port: 10064
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11036-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11036
  cipher: aes-128-cfb
- name: 🇷🇺:俄罗斯-ss-213.183.53.208:9046-可用-直连-完全不支持NF
  type: ss
  server: 213.183.53.208
  password: NvS8N4Vf8qAGPSCL
  port: 9046
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:24005-可用-中转:223.26.73.202-解锁台湾地区NF非自制剧
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 24005
  cipher: aes-128-cfb
- name: 🇷🇺:俄罗斯-ss-213.183.53.208:9040-可用-直连-完全不支持NF
  type: ss
  server: 213.183.53.208
  password: p9z5BVADH2YFs3MN
  port: 9040
  cipher: aes-256-cfb
- name: 🇷🇺:俄罗斯-ss-213.183.53.208:9025-可用-直连-完全不支持NF
  type: ss
  server: 213.183.53.208
  password: XPtzA9sCug3SPR4c
  port: 9025
  cipher: aes-256-cfb
- name: 🇳🇱:荷兰-ss-213.183.51.171:9053-可用-直连-仅支持荷兰地区NF自制剧
  type: ss
  server: 213.183.51.171
  password: SBM7R883jBmnqe6C
  port: 9053
  cipher: aes-256-cfb
- name: 🇷🇺:俄罗斯-ss-213.183.53.208:9000-可用-直连-完全不支持NF
  type: ss
  server: 213.183.53.208
  password: a3GFYt36Sm82Vys9
  port: 9000
  cipher: aes-256-cfb
- name: 🇳🇱:荷兰-ss-213.183.59.206:9094-可用-直连-仅支持荷兰地区NF自制剧
  type: ss
  server: 213.183.59.206
  password: rpgbNnU9rDDU4aWZ
  port: 9094
  cipher: aes-256-cfb
- name: 🇷🇺:俄罗斯-ss-213.183.53.177:9015-可用-直连-完全不支持NF
  type: ss
  server: 213.183.53.177
  password: ZpNDDKRu9MagNvaf
  port: 9015
  cipher: aes-256-cfb
- name: 🇳🇱:荷兰-ss-213.183.59.206:9038-可用-直连-仅支持荷兰地区NF自制剧
  type: ss
  server: 213.183.59.206
  password: gYCYXfkUQEs2TaJQ
  port: 9038
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:24073-被墙-中转:223.26.73.202-解锁台湾地区NF非自制剧
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 24073
  cipher: aes-128-cfb
- name: 🇷🇴:罗马尼亚-ss-185.126.116.119:9011-被墙-直连-解锁瑞士地区NF非自制剧
  type: ss
  server: 185.126.116.119
  password: M3t2ZEQcMGRWBjRa
  port: 9011
  cipher: aes-256-cfb
- name: 🇷🇴:罗马尼亚-ss-185.126.116.119:9031-被墙-直连-解锁瑞士地区NF非自制剧
  type: ss
  server: 185.126.116.119
  password: BwcAUZk8hUFAkDGN
  port: 9031
  cipher: aes-256-cfb
- name: 🇨🇦:加拿大-ss-72.140.224.197:801-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 801
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:802-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇷🇴:罗马尼亚-ss-185.126.116.119:9058-被墙-直连-解锁瑞士地区NF非自制剧
  type: ss
  server: 185.126.116.119
  password: dML2sfhbVwvtfNPe
  port: 9058
  cipher: aes-256-cfb
- name: 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  type: ss
  server: 213.169.137.221
  password: f8f7aCzcPKbsF8p3
  port: 989
  cipher: aes-256-cfb
- name: 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 31.133.100.49
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇷🇴:罗马尼亚-ss-185.126.116.119:9056-被墙-直连-解锁瑞士地区NF非自制剧
  type: ss
  server: 185.126.116.119
  password: rNBfNuuANFCAk7KB
  port: 9056
  cipher: aes-256-cfb
- name: 🇷🇴:罗马尼亚-ss-185.126.116.119:9025-被墙-直连-解锁瑞士地区NF非自制剧
  type: ss
  server: 185.126.116.119
  password: XPtzA9sCug3SPR4c
  port: 9025
  cipher: aes-256-cfb
- name: 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 83.229.73.60
  password: '8460400130'
  port: 50003
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.126.217
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.125.91
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-138.68.248.130:811-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 138.68.248.130
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇷🇺:俄罗斯-ssr-213.183.53.177:9094-可用-直连-完全不支持NF
  type: ssr
  server: 213.183.53.177
  password: rpgbNnU9rDDU4aWZ
  obfs: plain
  protocol: origin
  port: 9094
  cipher: aes-256-cfb
  protocol-param: ''
  obfs-param: ''

# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
proxy-groups:
  # 保留的自定义节点
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-ss-92.38.176.81:811-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.91.100.27:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.75.136.102:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.134.191:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.121.43.71:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.114.114.67:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.114.114.19:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-169.197.142.187:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.63.79:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.61.60:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.61.175:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-144.91.109.75:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-142.202.48.99:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-142.202.48.74:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-142.202.48.58:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-142.202.48.52:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-138.68.248.130:811-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-134.195.196.227:443-可用-直连-不支持Netflix
  - 🇷🇺:俄罗斯-ssr-213.183.53.177:9094-可用-直连-完全不支持NF
  - 🇷🇺:俄罗斯-ss-217.30.10.65:9008-可用-直连-仅支持波兰地区NF自制剧
  - 🇷🇺:俄罗斯-ss-213.183.53.208:9046-可用-直连-完全不支持NF
  - 🇷🇺:俄罗斯-ss-213.183.53.208:9041-可用-直连-完全不支持NF
  - 🇷🇺:俄罗斯-ss-213.183.53.208:9040-可用-直连-完全不支持NF
  - 🇷🇺:俄罗斯-ss-213.183.53.208:9025-可用-直连-完全不支持NF
  - 🇷🇺:俄罗斯-ss-213.183.53.208:9000-可用-直连-完全不支持NF
  - 🇷🇺:俄罗斯-ss-213.183.53.177:9015-可用-直连-完全不支持NF
  - 🇷🇺:俄罗斯-ss-185.4.65.6:21247-可用-中转:37.252.1.212-完全不支持NF
  - 🇳🇱:荷兰-ss-213.183.59.206:9094-可用-直连-仅支持荷兰地区NF自制剧
  - 🇳🇱:荷兰-ss-213.183.59.206:9038-可用-直连-仅支持荷兰地区NF自制剧
  - 🇳🇱:荷兰-ss-213.183.51.171:9053-可用-直连-仅支持荷兰地区NF自制剧
  - 🇳🇱:荷兰-ss-213.183.51.171:9010-可用-直连-仅支持荷兰地区NF自制剧
  - 🇨🇳:中国-ss-180.163.62.91:10064-可用-中转:129.227.4.80-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11036-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11033-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25252-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-14.29.124.168:24008-可用-中转:223.26.73.202-解锁台湾地区NF非自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24005-可用-中转:223.26.73.202-解锁台湾地区NF非自制剧
  - 🇨🇦:加拿大-ss-38.64.138.145:443-可用-直连-不支持Netflix
- name: 被墙代理组
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-ss-138.68.248.130:811-被墙-直连-解锁美国地区NF非自制剧
  - 🇷🇴:罗马尼亚-ss-185.126.116.119:9058-被墙-直连-解锁瑞士地区NF非自制剧
  - 🇷🇴:罗马尼亚-ss-185.126.116.119:9056-被墙-直连-解锁瑞士地区NF非自制剧
  - 🇷🇴:罗马尼亚-ss-185.126.116.119:9031-被墙-直连-解锁瑞士地区NF非自制剧
  - 🇷🇴:罗马尼亚-ss-185.126.116.119:9025-被墙-直连-解锁瑞士地区NF非自制剧
  - 🇷🇴:罗马尼亚-ss-185.126.116.119:9011-被墙-直连-解锁瑞士地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.171:800-被墙-中转:5.181.5.184-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:809-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:807-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:805-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:803-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:801-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  - 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24073-被墙-中转:223.26.73.202-解锁台湾地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:812-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:806-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:805-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:802-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:801-被墙-直连-解锁加拿大地区NF非自制剧
- name: 仅支持Netflix自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇷🇺:俄罗斯-ss-217.30.10.65:9008-可用-直连-仅支持波兰地区NF自制剧
  - 🇳🇱:荷兰-ss-213.183.59.206:9094-可用-直连-仅支持荷兰地区NF自制剧
  - 🇳🇱:荷兰-ss-213.183.59.206:9038-可用-直连-仅支持荷兰地区NF自制剧
  - 🇳🇱:荷兰-ss-213.183.51.171:9053-可用-直连-仅支持荷兰地区NF自制剧
  - 🇳🇱:荷兰-ss-213.183.51.171:9010-可用-直连-仅支持荷兰地区NF自制剧
- name: 解锁Netflix非自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇨🇳:中国-ss-14.29.124.168:24008-可用-中转:223.26.73.202-解锁台湾地区NF非自制剧
  - 🇨🇳:中国-ss-14.29.124.168:24005-可用-中转:223.26.73.202-解锁台湾地区NF非自制剧
- name: 入口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
  - PROXY
- name: 出口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 被墙代理组
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
- name: RELAY_PROXY
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: relay
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 入口代理组
  - 出口代理组
- name: NETFLIX_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Tiktok_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Bili_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
- name: IQiyi_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY

# 黑名单模式，命中规则使用代理
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
  # > Netflix
- DOMAIN-SUFFIX,netflix.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflix.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxext.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxso.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxvideo.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest0.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest1.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest2.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest3.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest4.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest5.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest6.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest7.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest8.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest9.com,NETFLIX_PROXY
  # Netflix测速网站
- DOMAIN-SUFFIX,fast.com,NETFLIX_PROXY
  # - RULE-SET,video_netflix,NETFLIX_PROXY
  # > TikTok
- PROCESS-NAME,com.ss.android.ugc.trill,Tiktok_PROXY
- DOMAIN-SUFFIX,byteoversea.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ibytedtos.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ipstatp.com,Tiktok_PROXY
- DOMAIN-SUFFIX,muscdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,musical.ly,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktok.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tik-tokapi.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokcdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokv.com,Tiktok_PROXY
  # - RULE-SET,video_tiktok,Tiktok_PROXY
  # > iQIYI
- DOMAIN-SUFFIX,iq.com,IQiyi_PROXY
- DOMAIN,intl.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-rcd.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-subscription.iqiyi.com,IQiyi_PROXY
  # - RULE-SET,video_iqiyi,IQiyi_PROXY
  # > Bilibili
- PROCESS-NAME,com.bilibili.app.in,Bili_PROXY
- PROCESS-NAME,tv.danmaku.bili,Bili_PROXY
- DOMAIN-SUFFIX,acg.tv,Bili_PROXY
- DOMAIN-SUFFIX,acgvideo.com,Bili_PROXY
- DOMAIN-SUFFIX,b23.tv,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.com,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.net,Bili_PROXY
- DOMAIN-SUFFIX,bilibili.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.net,Bili_PROXY
- DOMAIN-SUFFIX,bilivideo.com,Bili_PROXY
- DOMAIN-SUFFIX,hdslb.com,Bili_PROXY
- DOMAIN-SUFFIX,im9.com,Bili_PROXY
- DOMAIN-SUFFIX,smtcdns.net,Bili_PROXY
  # 后面追加规则
