port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
  - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - 8.8.8.8   # Google DNS over TCP
  - 1.1.1.1   # cloudflare DNS over TCP
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4
# 个人节点
proxies:
- name: 🇺🇸:美国-ss-38.68.135.18:5003-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: g5MeD6Ft3CWlJId
  port: 5003
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.18:8090-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: PCnnH6SQSnfoS27
  port: 8090
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.18:8009-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: XKFKl2rULjIp74
  port: 8009
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.18:5601-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: Y6R9pAtvxxzmGC
  port: 5601
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.18:6697-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: TEzjfAYq2IjtuoS
  port: 6697
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-45.66.134.176:806-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 806
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:805-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:809-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 809
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:802-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.168:25219-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25219
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25259-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25259
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25267-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25267
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25296-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25296
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25207-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25207
  cipher: aes-128-cfb
- name: 🇷🇺:俄罗斯-ss-217.30.10.67:9043-可用-直连-不支持Netflix
  type: ss
  server: 217.30.10.67
  password: HSZuyJQcWe8dxNdF
  port: 9043
  cipher: aes-256-cfb
- name: 🇳🇱:荷兰-ss-213.183.59.229:9056-可用-直连-不支持Netflix
  type: ss
  server: 213.183.59.229
  password: rNBfNuuANFCAk7KB
  port: 9056
  cipher: aes-256-cfb
- name: 🇷🇺:俄罗斯-ss-217.30.10.67:9037-可用-直连-不支持Netflix
  type: ss
  server: 217.30.10.67
  password: TN2YqghxeFDKZfLU
  port: 9037
  cipher: aes-256-cfb
- name: 🇩🇪:德国-ss-165.22.73.126:23335-可用-直连-不支持Netflix
  type: ss
  server: 165.22.73.126
  password: 7d99ae502227454ea998d71e4b62a388
  port: 23335
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11037-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11037
  cipher: aes-128-cfb
- name: 🇳🇱:荷兰-ss-213.183.59.229:9053-可用-直连-不支持Netflix
  type: ss
  server: 213.183.59.229
  password: SBM7R883jBmnqe6C
  port: 9053
  cipher: aes-256-cfb
- name: 🇳🇱:荷兰-ss-213.183.59.229:9020-可用-直连-不支持Netflix
  type: ss
  server: 213.183.59.229
  password: BNmAXXxAHYpTRdzu
  port: 9020
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11033-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11033
  cipher: aes-128-cfb
- name: 🇯🇵:日本-ss-45.66.134.176:810-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 810
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 31.133.100.49
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 83.229.73.60
  password: '8460400130'
  port: 50003
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.126.217
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.125.91
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇨🇳:中国-vmess-lc-hk03-direct01.lc-hk03.lc-node.com:443-可用-中转:60.249.117.110-不支持Netflix
  type: vmess
  server: lc-hk03-direct01.lc-hk03.lc-node.com
  network: ws
  port: 443
  uuid: ec736482-173e-3eff-9114-b49df8056e7d
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /
- name: 🇷🇺:俄罗斯-vmess-usa23.884899.cf:443-可用-中转:92.119.129.96-完全不支持NF
  type: vmess
  server: usa23.884899.cf
  network: ws
  port: 443
  uuid: 3df66137-a428-429c-a858-8b150721b354
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /youtbue@bai-piao-wang-zhe_vws
- name: 🇺🇸:美国-vmess-v116.v2dns.bar:80-可用-中转:45.129.2.68-完全不支持NF
  type: vmess
  server: v116.v2dns.bar
  network: ws
  port: 80
  uuid: c97cf46e-1554-36cb-8b36-c3556b883dc4
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /v116-DtoEwAEX
- name: 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65038-可用-中转:103.181.164.27-不支持Netflix
  type: vmess
  server: cn05.downloadmovie.cn
  network: ws
  port: 65038
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65025-可用-中转:211.22.180.40-不支持Netflix
  type: vmess
  server: cn04.downloadmovie.cn
  network: ws
  port: 65025
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn03.downloadmovie.cn:65027-可用-中转:103.181.164.27-不支持Netflix
  type: vmess
  server: cn03.downloadmovie.cn
  network: ws
  port: 65027
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65028-可用-中转:103.181.164.27-不支持Netflix
  type: vmess
  server: cn04.downloadmovie.cn
  network: ws
  port: 65028
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-best03.downloadmovie.cn:65081-可用-中转:116.204.182.25-不支持Netflix
  type: vmess
  server: best03.downloadmovie.cn
  network: ws
  port: 65081
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇺🇸:美国-vmess-v2.tgfaka.com:8443-可用-中转:45.8.230.253-不支持Netflix
  type: vmess
  server: v2.tgfaka.com
  network: ws
  port: 8443
  uuid: 00b19c02-bc00-440a-a397-faf70ac3f44e
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /api/v3/download.getFile
- name: 🇦🇺:澳大利亚-vmess-vau1.0bad.com:443-可用-中转:172.105.182.64-仅支持澳大利亚地区NF自制剧
  type: vmess
  server: vau1.0bad.com
  network: ws
  port: 443
  uuid: 927094d3-d678-4763-8591-e240d0bcae87
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /chat
- name: 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65026-可用-中转:211.22.180.1-不支持Netflix
  type: vmess
  server: cn05.downloadmovie.cn
  network: ws
  port: 65026
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇺🇸:美国-vmess-lu1.gogogoo.cyou:443-可用-中转:107.189.11.246-仅支持卢森堡地区NF自制剧
  type: vmess
  server: lu1.gogogoo.cyou
  network: ws
  port: 443
  uuid: db5d1aa3-908b-44d1-be0a-4e6a8d4e4cda
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /go
- name: 🇺🇸:美国-vmess-v2ray.wefuckgfw.ga:2096-可用-中转:45.90.58.175-仅支持瑞士地区NF自制剧
  type: vmess
  server: v2ray.wefuckgfw.ga
  network: ws
  port: 2096
  uuid: dd5f3ea6-e219-4934-826b-41b176c7a88e
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /H8VswtUJ/
- name: 🇺🇸:美国-vmess-vus2.0bad.com:443-可用-中转:45.33.63.235-仅支持美国地区NF自制剧
  type: vmess
  server: vus2.0bad.com
  network: ws
  port: 443
  uuid: 927094d3-d678-4763-8591-e240d0bcae87
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /chat
- name: 🇺🇸:美国-vmess-hk18.bp777.buzz:21665-可用-中转:138.2.121.184-解锁韩国地区NF非自制剧
  type: vmess
  server: hk18.bp777.buzz
  network: ws
  port: 21665
  uuid: 07898420-dc51-4daf-99dd-0cbe007172ee
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇺🇸:美国-vmess-v1.tgfaka.com:8443-可用-中转:193.38.51.192-不支持Netflix
  type: vmess
  server: v1.tgfaka.com
  network: ws
  port: 8443
  uuid: 00b19c02-bc00-440a-a397-faf70ac3f44e
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /api/v3/download.getFile
- name: 🇺🇸:美国-vmess-v3.tgfaka.com:8443-可用-中转:176.119.156.229-不支持Netflix
  type: vmess
  server: v3.tgfaka.com
  network: ws
  port: 8443
  uuid: 00b19c02-bc00-440a-a397-faf70ac3f44e
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /api/v3/download.getFile

# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
proxy-groups:
  # 保留的自定义节点
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-vus2.0bad.com:443-可用-中转:45.33.63.235-仅支持美国地区NF自制剧
  - 🇺🇸:美国-vmess-v3.tgfaka.com:8443-可用-中转:176.119.156.229-不支持Netflix
  - 🇺🇸:美国-vmess-v2ray.wefuckgfw.ga:2096-可用-中转:45.90.58.175-仅支持瑞士地区NF自制剧
  - 🇺🇸:美国-vmess-v2.tgfaka.com:8443-可用-中转:45.8.230.253-不支持Netflix
  - 🇺🇸:美国-vmess-v116.v2dns.bar:80-可用-中转:45.129.2.68-完全不支持NF
  - 🇺🇸:美国-vmess-v1.tgfaka.com:8443-可用-中转:193.38.51.192-不支持Netflix
  - 🇺🇸:美国-vmess-lu1.gogogoo.cyou:443-可用-中转:107.189.11.246-仅支持卢森堡地区NF自制剧
  - 🇺🇸:美国-vmess-hk18.bp777.buzz:21665-可用-中转:138.2.121.184-解锁韩国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.135.18:8090-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:8009-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:6697-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:5601-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:5003-可用-直连-不支持Netflix
  - 🇷🇺:俄罗斯-vmess-usa23.884899.cf:443-可用-中转:92.119.129.96-完全不支持NF
  - 🇷🇺:俄罗斯-ss-217.30.10.67:9043-可用-直连-不支持Netflix
  - 🇷🇺:俄罗斯-ss-217.30.10.67:9037-可用-直连-不支持Netflix
  - 🇳🇱:荷兰-ss-213.183.59.229:9056-可用-直连-不支持Netflix
  - 🇳🇱:荷兰-ss-213.183.59.229:9053-可用-直连-不支持Netflix
  - 🇳🇱:荷兰-ss-213.183.59.229:9020-可用-直连-不支持Netflix
  - 🇩🇪:德国-ss-165.22.73.126:23335-可用-直连-不支持Netflix
  - 🇨🇳:中国-vmess-lc-hk03-direct01.lc-hk03.lc-node.com:443-可用-中转:60.249.117.110-不支持Netflix
  - 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65038-可用-中转:103.181.164.27-不支持Netflix
  - 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65026-可用-中转:211.22.180.1-不支持Netflix
  - 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65028-可用-中转:103.181.164.27-不支持Netflix
  - 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65025-可用-中转:211.22.180.40-不支持Netflix
  - 🇨🇳:中国-vmess-cn03.downloadmovie.cn:65027-可用-中转:103.181.164.27-不支持Netflix
  - 🇨🇳:中国-vmess-best03.downloadmovie.cn:65081-可用-中转:116.204.182.25-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11037-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11033-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25296-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25267-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25259-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25219-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25207-可用-直连-不支持Netflix
  - 🇦🇺:澳大利亚-vmess-vau1.0bad.com:443-可用-中转:172.105.182.64-仅支持澳大利亚地区NF自制剧
- name: 被墙代理组
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:810-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:809-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:806-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:805-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:802-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
- name: 仅支持Netflix自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-vus2.0bad.com:443-可用-中转:45.33.63.235-仅支持美国地区NF自制剧
  - 🇺🇸:美国-vmess-v2ray.wefuckgfw.ga:2096-可用-中转:45.90.58.175-仅支持瑞士地区NF自制剧
  - 🇺🇸:美国-vmess-lu1.gogogoo.cyou:443-可用-中转:107.189.11.246-仅支持卢森堡地区NF自制剧
  - 🇦🇺:澳大利亚-vmess-vau1.0bad.com:443-可用-中转:172.105.182.64-仅支持澳大利亚地区NF自制剧
- name: 解锁Netflix非自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-hk18.bp777.buzz:21665-可用-中转:138.2.121.184-解锁韩国地区NF非自制剧
- name: 入口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
  - PROXY
- name: 出口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 被墙代理组
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
- name: RELAY_PROXY
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: relay
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 入口代理组
  - 出口代理组
- name: NETFLIX_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Tiktok_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Bili_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
- name: IQiyi_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY

# 黑名单模式，命中规则使用代理
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
  # > Netflix
- DOMAIN-SUFFIX,netflix.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflix.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxext.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxso.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxvideo.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest0.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest1.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest2.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest3.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest4.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest5.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest6.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest7.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest8.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest9.com,NETFLIX_PROXY
  # Netflix测速网站
- DOMAIN-SUFFIX,fast.com,NETFLIX_PROXY
  # - RULE-SET,video_netflix,NETFLIX_PROXY
  # > TikTok
- PROCESS-NAME,com.ss.android.ugc.trill,Tiktok_PROXY
- DOMAIN-SUFFIX,byteoversea.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ibytedtos.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ipstatp.com,Tiktok_PROXY
- DOMAIN-SUFFIX,muscdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,musical.ly,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktok.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tik-tokapi.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokcdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokv.com,Tiktok_PROXY
  # - RULE-SET,video_tiktok,Tiktok_PROXY
  # > iQIYI
- DOMAIN-SUFFIX,iq.com,IQiyi_PROXY
- DOMAIN,intl.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-rcd.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-subscription.iqiyi.com,IQiyi_PROXY
  # - RULE-SET,video_iqiyi,IQiyi_PROXY
  # > Bilibili
- PROCESS-NAME,com.bilibili.app.in,Bili_PROXY
- PROCESS-NAME,tv.danmaku.bili,Bili_PROXY
- DOMAIN-SUFFIX,acg.tv,Bili_PROXY
- DOMAIN-SUFFIX,acgvideo.com,Bili_PROXY
- DOMAIN-SUFFIX,b23.tv,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.com,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.net,Bili_PROXY
- DOMAIN-SUFFIX,bilibili.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.net,Bili_PROXY
- DOMAIN-SUFFIX,bilivideo.com,Bili_PROXY
- DOMAIN-SUFFIX,hdslb.com,Bili_PROXY
- DOMAIN-SUFFIX,im9.com,Bili_PROXY
- DOMAIN-SUFFIX,smtcdns.net,Bili_PROXY
  # 后面追加规则
