port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
  - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - 8.8.8.8   # Google DNS over TCP
  - 1.1.1.1   # cloudflare DNS over TCP
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4
# 个人节点
proxies:
- name: 🇺🇸:美国-ss-138.68.248.130:811-可用-直连-不支持Netflix
  type: ss
  server: 138.68.248.130
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇬🇧:英国-ss-178.62.16.161:811-可用-直连-不支持Netflix
  type: ss
  server: 178.62.16.161
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.168:25219-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25219
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25218-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25218
  cipher: aes-128-cfb
- name: 🇺🇸:美国-ss-167.88.61.2:807-可用-直连-不支持Netflix
  type: ss
  server: 167.88.61.2
  password: G!yBwPWH3Vao
  port: 807
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.168:25220-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25220
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:24005-可用-中转:223.26.73.202-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 24005
  cipher: aes-128-cfb
- name: 🇺🇸:美国-ss-51.195.136.209:50004-可用-直连-不支持Netflix
  type: ss
  server: 51.195.136.209
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25280-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25280
  cipher: aes-128-cfb
- name: 🇺🇸:美国-ss-167.88.61.2:812-可用-直连-不支持Netflix
  type: ss
  server: 167.88.61.2
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-167.88.61.2:802-可用-直连-不支持Netflix
  type: ss
  server: 167.88.61.2
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-89.31.126.171:800-可用-中转:5.181.5.184-不支持Netflix
  type: ss
  server: 89.31.126.171
  password: G!yBwPWH3Vao
  port: 800
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-167.88.61.2:803-可用-直连-不支持Netflix
  type: ss
  server: 167.88.61.2
  password: G!yBwPWH3Vao
  port: 803
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.174:11012-可用-中转:129.227.144.194-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11012
  cipher: aes-128-cfb
- name: 🇫🇷:法国-ss-195.154.200.150:2376-可用-直连-不支持Netflix
  type: ss
  server: 195.154.200.150
  password: faBAoD54k87UJG7
  port: 2376
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.61.2:808-可用-直连-不支持Netflix
  type: ss
  server: 167.88.61.2
  password: G!yBwPWH3Vao
  port: 808
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-138.197.166.205:811-可用-直连-不支持Netflix
  type: ss
  server: 138.197.166.205
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.174:11018-可用-中转:129.227.144.194-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11018
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.174:11031-可用-中转:129.227.144.195-不支持Netflix
  type: ss
  server: 14.29.124.174
  password: QazEdcTgb159@$*
  port: 11031
  cipher: aes-128-cfb
- name: 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  type: ss
  server: 213.169.137.221
  password: f8f7aCzcPKbsF8p3
  port: 989
  cipher: aes-256-cfb
- name: 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 31.133.100.49
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇷🇴:罗马尼亚-ss-185.126.116.119:9025-被墙-直连-解锁瑞士地区NF非自制剧
  type: ss
  server: 185.126.116.119
  password: XPtzA9sCug3SPR4c
  port: 9025
  cipher: aes-256-cfb
- name: 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 83.229.73.60
  password: '8460400130'
  port: 50003
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.126.217
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.125.91
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ssr-14.29.124.168:24001-被墙-中转:223.26.73.202-解锁台湾地区NF非自制剧
  type: ssr
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  obfs: plain
  protocol: origin
  port: 24001
  cipher: aes-128-cfb
  protocol-param: ''
  obfs-param: ''
- name: 🇺🇸:美国-vmess-v116.v2dns.bar:80-可用-中转:45.129.2.68-完全不支持NF
  type: vmess
  server: v116.v2dns.bar
  network: ws
  port: 80
  uuid: c97cf46e-1554-36cb-8b36-c3556b883dc4
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /v116-DtoEwAEX
- name: 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65038-可用-中转:103.181.164.26-不支持Netflix
  type: vmess
  server: cn05.downloadmovie.cn
  network: ws
  port: 65038
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇺🇸:美国-vmess-jp.azzhuangaping.tw:80-可用-中转:8.37.43.73-仅支持日本地区NF自制剧
  type: vmess
  server: jp.azzhuangaping.tw
  network: ws
  port: 80
  uuid: cebeb605-6e5e-3a13-a0ce-1ee247f91bf7
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /adobe
- name: 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65025-可用-中转:211.22.180.40-不支持Netflix
  type: vmess
  server: cn04.downloadmovie.cn
  network: ws
  port: 65025
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn03.downloadmovie.cn:65027-可用-中转:103.181.164.26-不支持Netflix
  type: vmess
  server: cn03.downloadmovie.cn
  network: ws
  port: 65027
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65028-可用-中转:103.181.164.26-不支持Netflix
  type: vmess
  server: cn04.downloadmovie.cn
  network: ws
  port: 65028
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-best03.downloadmovie.cn:65081-可用-中转:116.204.182.25-不支持Netflix
  type: vmess
  server: best03.downloadmovie.cn
  network: ws
  port: 65081
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65026-可用-中转:211.22.180.1-不支持Netflix
  type: vmess
  server: cn05.downloadmovie.cn
  network: ws
  port: 65026
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇺🇸:美国-vmess-free-godlikeanyone.koyeb.app:443-可用-中转:147.75.102.249-仅支持荷兰地区NF自制剧
  type: vmess
  server: free-godlikeanyone.koyeb.app
  network: ws
  port: 443
  uuid: b7b1f689-f82e-4ce4-97e7-8a8997370e44
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /b7b1f689-f82e-4ce4-97e7-8a8997370e44-vmess
- name: 🇨🇳:中国-vmess-best02.downloadmovie.cn:65081-可用-中转:116.204.182.25-不支持Netflix
  type: vmess
  server: best02.downloadmovie.cn
  network: ws
  port: 65081
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65036-可用-中转:211.22.180.127-不支持Netflix
  type: vmess
  server: cn04.downloadmovie.cn
  network: ws
  port: 65036
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket
- name: 🇨🇳:中国-vmess-cn03.downloadmovie.cn:65041-可用-中转:103.148.72.41-不支持Netflix
  type: vmess
  server: cn03.downloadmovie.cn
  network: ws
  port: 65041
  uuid: 0253b574-8020-3186-a647-0267295ac9bb
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /rocket

# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
proxy-groups:
  # 保留的自定义节点
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-v116.v2dns.bar:80-可用-中转:45.129.2.68-完全不支持NF
  - 🇺🇸:美国-vmess-jp.azzhuangaping.tw:80-可用-中转:8.37.43.73-仅支持日本地区NF自制剧
  - 🇺🇸:美国-vmess-free-godlikeanyone.koyeb.app:443-可用-中转:147.75.102.249-仅支持荷兰地区NF自制剧
  - 🇺🇸:美国-ss-51.195.136.209:50004-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.61.2:812-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.61.2:808-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.61.2:807-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.61.2:803-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-167.88.61.2:802-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-138.68.248.130:811-可用-直连-不支持Netflix
  - 🇯🇵:日本-ss-89.31.126.171:800-可用-中转:5.181.5.184-不支持Netflix
  - 🇬🇧:英国-ss-178.62.16.161:811-可用-直连-不支持Netflix
  - 🇫🇷:法国-ss-195.154.200.150:2376-可用-直连-不支持Netflix
  - 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65038-可用-中转:103.181.164.26-不支持Netflix
  - 🇨🇳:中国-vmess-cn05.downloadmovie.cn:65026-可用-中转:211.22.180.1-不支持Netflix
  - 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65036-可用-中转:211.22.180.127-不支持Netflix
  - 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65028-可用-中转:103.181.164.26-不支持Netflix
  - 🇨🇳:中国-vmess-cn04.downloadmovie.cn:65025-可用-中转:211.22.180.40-不支持Netflix
  - 🇨🇳:中国-vmess-cn03.downloadmovie.cn:65041-可用-中转:103.148.72.41-不支持Netflix
  - 🇨🇳:中国-vmess-cn03.downloadmovie.cn:65027-可用-中转:103.181.164.26-不支持Netflix
  - 🇨🇳:中国-vmess-best03.downloadmovie.cn:65081-可用-中转:116.204.182.25-不支持Netflix
  - 🇨🇳:中国-vmess-best02.downloadmovie.cn:65081-可用-中转:116.204.182.25-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11031-可用-中转:129.227.144.195-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11018-可用-中转:129.227.144.194-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.174:11012-可用-中转:129.227.144.194-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25280-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25220-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25219-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25218-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:24005-可用-中转:223.26.73.202-不支持Netflix
  - 🇨🇦:加拿大-ss-138.197.166.205:811-可用-直连-不支持Netflix
- name: 被墙代理组
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇷🇴:罗马尼亚-ss-185.126.116.119:9025-被墙-直连-解锁瑞士地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  - 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  - 🇨🇳:中国-ssr-14.29.124.168:24001-被墙-中转:223.26.73.202-解锁台湾地区NF非自制剧
- name: 仅支持Netflix自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-jp.azzhuangaping.tw:80-可用-中转:8.37.43.73-仅支持日本地区NF自制剧
  - 🇺🇸:美国-vmess-free-godlikeanyone.koyeb.app:443-可用-中转:147.75.102.249-仅支持荷兰地区NF自制剧
- name: 解锁Netflix非自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
- name: 入口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
  - PROXY
- name: 出口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 被墙代理组
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
- name: RELAY_PROXY
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: relay
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 入口代理组
  - 出口代理组
- name: NETFLIX_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Tiktok_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Bili_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
- name: IQiyi_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY

# 黑名单模式，命中规则使用代理
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
  # > Netflix
- DOMAIN-SUFFIX,netflix.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflix.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxext.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxso.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxvideo.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest0.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest1.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest2.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest3.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest4.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest5.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest6.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest7.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest8.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest9.com,NETFLIX_PROXY
  # Netflix测速网站
- DOMAIN-SUFFIX,fast.com,NETFLIX_PROXY
  # - RULE-SET,video_netflix,NETFLIX_PROXY
  # > TikTok
- PROCESS-NAME,com.ss.android.ugc.trill,Tiktok_PROXY
- DOMAIN-SUFFIX,byteoversea.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ibytedtos.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ipstatp.com,Tiktok_PROXY
- DOMAIN-SUFFIX,muscdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,musical.ly,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktok.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tik-tokapi.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokcdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokv.com,Tiktok_PROXY
  # - RULE-SET,video_tiktok,Tiktok_PROXY
  # > iQIYI
- DOMAIN-SUFFIX,iq.com,IQiyi_PROXY
- DOMAIN,intl.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-rcd.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-subscription.iqiyi.com,IQiyi_PROXY
  # - RULE-SET,video_iqiyi,IQiyi_PROXY
  # > Bilibili
- PROCESS-NAME,com.bilibili.app.in,Bili_PROXY
- PROCESS-NAME,tv.danmaku.bili,Bili_PROXY
- DOMAIN-SUFFIX,acg.tv,Bili_PROXY
- DOMAIN-SUFFIX,acgvideo.com,Bili_PROXY
- DOMAIN-SUFFIX,b23.tv,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.com,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.net,Bili_PROXY
- DOMAIN-SUFFIX,bilibili.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.net,Bili_PROXY
- DOMAIN-SUFFIX,bilivideo.com,Bili_PROXY
- DOMAIN-SUFFIX,hdslb.com,Bili_PROXY
- DOMAIN-SUFFIX,im9.com,Bili_PROXY
- DOMAIN-SUFFIX,smtcdns.net,Bili_PROXY
  # 后面追加规则
