port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
  - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - 8.8.8.8   # Google DNS over TCP
  - 1.1.1.1   # cloudflare DNS over TCP
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4
# 个人节点
proxies:
- name: 🇺🇸:美国-ss-38.68.135.18:8009-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: XKFKl2rULjIp74
  port: 8009
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.136.34:8091-可用-直连-不支持Netflix
  type: ss
  server: 38.75.136.34
  password: PCnnH6SQSnfoS27
  port: 8091
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.91.107.37:5003-可用-直连-不支持Netflix
  type: ss
  server: 38.91.107.37
  password: g5MeD6Ft3CWlJId
  port: 5003
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.18:6697-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: TEzjfAYq2IjtuoS
  port: 6697
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.136.34:9101-可用-直连-不支持Netflix
  type: ss
  server: 38.75.136.34
  password: e4FCWrgpkji3QY
  port: 9101
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.136.34:8090-可用-直连-不支持Netflix
  type: ss
  server: 38.75.136.34
  password: PCnnH6SQSnfoS27
  port: 8090
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.121.43.204:8009-可用-直连-不支持Netflix
  type: ss
  server: 38.121.43.204
  password: XKFKl2rULjIp74
  port: 8009
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.136.34:5500-可用-直连-不支持Netflix
  type: ss
  server: 38.75.136.34
  password: KixLvKzwjekG00rm
  port: 5500
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.121.43.204:8119-可用-直连-不支持Netflix
  type: ss
  server: 38.121.43.204
  password: cdBIDV42DCwnfIN
  port: 8119
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.18:5601-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: Y6R9pAtvxxzmGC
  port: 5601
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.18:5003-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: g5MeD6Ft3CWlJId
  port: 5003
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-183.232.158.120:7401-可用-中转:103.142.140.57-不支持Netflix
  type: ss
  server: 183.232.158.120
  password: c0b4efb0-ab81-46f8-87af-815b62351089
  port: 7401
  cipher: aes-128-gcm
- name: 🇯🇵:日本-ss-45.66.134.176:806-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 806
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:807-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 807
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-37.120.219.218:812-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 37.120.219.218
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.196:808-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 808
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:810-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 810
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.196:802-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.196:812-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.196:800-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 800
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-138.68.248.130:811-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 138.68.248.130
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:801-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 801
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.196:805-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.135.18:5500-可用-直连-不支持Netflix
  type: ss
  server: 38.68.135.18
  password: KixLvKzwjekG00rm
  port: 5500
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-183.232.158.67:9201-可用-中转:185.212.61.50-不支持Netflix
  type: ss
  server: 183.232.158.67
  password: 2bf86435908573620556efdd3a4883ad
  port: 9201
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.136.34:8080-可用-直连-不支持Netflix
  type: ss
  server: 38.75.136.34
  password: KixLvKzwjekG00rm
  port: 8080
  cipher: aes-256-gcm
- name: 🇨🇳:中国-ss-183.232.158.67:9521-可用-中转:103.81.87.203-不支持Netflix
  type: ss
  server: 183.232.158.67
  password: 6071345b7a58134cc962c96f7a502ae6
  port: 9521
  cipher: aes-256-gcm
- name: 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 83.229.73.60
  password: '8460400130'
  port: 50003
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.126.217
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇺🇸:美国-ss-38.68.134.135:809-被墙-中转:38.68.134.196-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.135
  password: G!yBwPWH3Vao
  port: 809
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-37.120.219.218:809-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 37.120.219.218
  password: G!yBwPWH3Vao
  port: 809
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-45.66.134.176:803-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  type: ss
  server: 45.66.134.176
  password: G!yBwPWH3Vao
  port: 803
  cipher: chacha20-ietf-poly1305
- name: 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.125.91
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 31.133.100.49
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇨🇳:中国-vmess-106.12.168.13:23117-可用-直连-完全不支持NF
  type: vmess
  server: 106.12.168.13
  network: ws
  port: 23117
  uuid: 6479ce34-0355-422d-d07e-d74116866fd2
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇸🇬:新加坡-vmess-165.22.60.91:443-可用-直连-不支持Netflix
  type: vmess
  server: 165.22.60.91
  network: ws
  port: 443
  uuid: bcaf6b8f-0acb-4ffd-86ad-8f13e7dfe436
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /cctv13/hd.m3u8
- name: 🇺🇸:美国-vmess-129.150.46.8:36277-可用-直连-解锁新加坡地区NF非自制剧
  type: vmess
  server: 129.150.46.8
  network: ws
  port: 36277
  uuid: f3d972b0-aa7f-499d-85cd-c0c26f9cc15f
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇺🇸:美国-vmess-192.9.139.253:443-可用-直连-不支持Netflix
  type: vmess
  server: 192.9.139.253
  network: ws
  port: 443
  uuid: 157ab24c-2f02-44d2-b211-6d70612c9f64
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /cctv13/hd.m3u8
- name: 🇨🇳:中国-vmess-106.12.168.13:13156-可用-直连-完全不支持NF
  type: vmess
  server: 106.12.168.13
  network: ws
  port: 13156
  uuid: 9bf4cba4-9e9e-4da4-8e65-f7c487c539df
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-120.240.55.137:38401-可用-中转:104.249.174.138-不支持Netflix
  type: vmess
  server: 120.240.55.137
  network: ws
  port: 38401
  uuid: 79386685-16da-327c-9e14-aa6d702d86bc
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /hls/cctv5phd.m3u8
- name: 🇨🇳:中国-vmess-120.240.55.137:38701-可用-中转:194.233.66.47-不支持Netflix
  type: vmess
  server: 120.240.55.137
  network: ws
  port: 38701
  uuid: 79386685-16da-327c-9e14-aa6d702d86bc
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /hls/cctv5phd.m3u8
- name: 🇨🇳:中国-vmess-124.223.44.153:80-可用-直连-完全不支持NF
  type: vmess
  server: 124.223.44.153
  network: ws
  port: 80
  uuid: 8017dfd8-f239-4ec6-e2dd-416189856438
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-47.93.231.218:53022-可用-直连-完全不支持NF
  type: vmess
  server: 47.93.231.218
  network: ws
  port: 53022
  uuid: 95fd7642-2160-4528-e909-3d526b533013
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-110.42.138.122:18080-可用-直连-完全不支持NF
  type: vmess
  server: 110.42.138.122
  network: ws
  port: 18080
  uuid: 6a9a236c-e99b-44d8-b414-bbcd6e7b1465
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-119.91.223.167:80-可用-直连-完全不支持NF
  type: vmess
  server: 119.91.223.167
  network: ws
  port: 80
  uuid: 5087e6ea-b650-443e-923f-b754661b8c47
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-49.234.34.180:443-可用-直连-完全不支持NF
  type: vmess
  server: 49.234.34.180
  network: ws
  port: 443
  uuid: 6e0a01f3-4fce-4cdd-ab05-ee5d2254b058
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-1.15.183.29:38555-可用-直连-完全不支持NF
  type: vmess
  server: 1.15.183.29
  network: ws
  port: 38555
  uuid: 67d4219f-01d1-4e8f-c127-73b6dc4fa3a4
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-120.240.55.137:38201-可用-中转:61.224.86.48-不支持Netflix
  type: vmess
  server: 120.240.55.137
  network: ws
  port: 38201
  uuid: 79386685-16da-327c-9e14-aa6d702d86bc
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /hls/cctv5phd.m3u8

# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
proxy-groups:
  # 保留的自定义节点
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-192.9.139.253:443-可用-直连-不支持Netflix
  - 🇺🇸:美国-vmess-129.150.46.8:36277-可用-直连-解锁新加坡地区NF非自制剧
  - 🇺🇸:美国-ss-38.91.107.37:5003-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.75.136.34:9101-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.75.136.34:8091-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.75.136.34:8090-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.75.136.34:8080-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.75.136.34:5500-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:8009-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:6697-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:5601-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:5500-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.68.135.18:5003-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.121.43.204:8119-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-38.121.43.204:8009-可用-直连-不支持Netflix
  - 🇸🇬:新加坡-vmess-165.22.60.91:443-可用-直连-不支持Netflix
  - 🇨🇳:中国-vmess-49.234.34.180:443-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-47.93.231.218:53022-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-124.223.44.153:80-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-120.240.55.137:38701-可用-中转:194.233.66.47-不支持Netflix
  - 🇨🇳:中国-vmess-120.240.55.137:38401-可用-中转:104.249.174.138-不支持Netflix
  - 🇨🇳:中国-vmess-120.240.55.137:38201-可用-中转:61.224.86.48-不支持Netflix
  - 🇨🇳:中国-vmess-119.91.223.167:80-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-110.42.138.122:18080-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-106.12.168.13:23117-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-106.12.168.13:13156-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-1.15.183.29:38555-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-183.232.158.67:9521-可用-中转:103.81.87.203-不支持Netflix
  - 🇨🇳:中国-ss-183.232.158.67:9201-可用-中转:185.212.61.50-不支持Netflix
  - 🇨🇳:中国-ss-183.232.158.120:7401-可用-中转:103.142.140.57-不支持Netflix
- name: 被墙代理组
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-ss-38.68.134.196:812-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:808-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:805-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:802-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:800-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.135:809-被墙-中转:38.68.134.196-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-37.120.219.218:812-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-37.120.219.218:809-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-138.68.248.130:811-被墙-直连-解锁美国地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:810-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:807-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:806-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:803-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-45.66.134.176:801-被墙-中转:185.168.20.250-解锁日本地区NF非自制剧
  - 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.125.91:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
- name: 仅支持Netflix自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
- name: 解锁Netflix非自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-129.150.46.8:36277-可用-直连-解锁新加坡地区NF非自制剧
- name: 入口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
  - PROXY
- name: 出口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 被墙代理组
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
- name: RELAY_PROXY
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: relay
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 入口代理组
  - 出口代理组
- name: NETFLIX_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Tiktok_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Bili_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
- name: IQiyi_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY

# 黑名单模式，命中规则使用代理
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
  # > Netflix
- DOMAIN-SUFFIX,netflix.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflix.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxext.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxso.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxvideo.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest0.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest1.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest2.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest3.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest4.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest5.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest6.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest7.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest8.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest9.com,NETFLIX_PROXY
  # Netflix测速网站
- DOMAIN-SUFFIX,fast.com,NETFLIX_PROXY
  # - RULE-SET,video_netflix,NETFLIX_PROXY
  # > TikTok
- PROCESS-NAME,com.ss.android.ugc.trill,Tiktok_PROXY
- DOMAIN-SUFFIX,byteoversea.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ibytedtos.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ipstatp.com,Tiktok_PROXY
- DOMAIN-SUFFIX,muscdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,musical.ly,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktok.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tik-tokapi.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokcdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokv.com,Tiktok_PROXY
  # - RULE-SET,video_tiktok,Tiktok_PROXY
  # > iQIYI
- DOMAIN-SUFFIX,iq.com,IQiyi_PROXY
- DOMAIN,intl.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-rcd.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-subscription.iqiyi.com,IQiyi_PROXY
  # - RULE-SET,video_iqiyi,IQiyi_PROXY
  # > Bilibili
- PROCESS-NAME,com.bilibili.app.in,Bili_PROXY
- PROCESS-NAME,tv.danmaku.bili,Bili_PROXY
- DOMAIN-SUFFIX,acg.tv,Bili_PROXY
- DOMAIN-SUFFIX,acgvideo.com,Bili_PROXY
- DOMAIN-SUFFIX,b23.tv,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.com,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.net,Bili_PROXY
- DOMAIN-SUFFIX,bilibili.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.net,Bili_PROXY
- DOMAIN-SUFFIX,bilivideo.com,Bili_PROXY
- DOMAIN-SUFFIX,hdslb.com,Bili_PROXY
- DOMAIN-SUFFIX,im9.com,Bili_PROXY
- DOMAIN-SUFFIX,smtcdns.net,Bili_PROXY
  # 后面追加规则
