port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
  - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - 8.8.8.8   # Google DNS over TCP
  - 1.1.1.1   # cloudflare DNS over TCP
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4
# 个人节点
proxies:
- name: 🇺🇸:美国-ss-92.38.176.81:811-可用-直连-不支持Netflix
  type: ss
  server: 92.38.176.81
  password: Ultr@r00t_2017
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-169.197.141.5:3306-可用-直连-不支持Netflix
  type: ss
  server: 169.197.141.5
  password: Y6R9pAtvxxzmGC
  port: 3306
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-134.195.196.85:5001-可用-直连-不支持Netflix
  type: ss
  server: 134.195.196.85
  password: Y6R9pAtvxxzmGC
  port: 5001
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-196.247.59.154:809-可用-直连-不支持Netflix
  type: ss
  server: 196.247.59.154
  password: G!yBwPWH3Vao
  port: 809
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-ss-14.29.124.168:25284-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25284
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25251-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25251
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25272-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25272
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25289-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25289
  cipher: aes-128-cfb
- name: 🇨🇳:中国-ss-14.29.124.168:25256-可用-直连-不支持Netflix
  type: ss
  server: 14.29.124.168
  password: QazEdcTgb159@$*
  port: 25256
  cipher: aes-128-cfb
- name: 🇨🇦:加拿大-ss-196.247.59.154:801-可用-直连-不支持Netflix
  type: ss
  server: 196.247.59.154
  password: G!yBwPWH3Vao
  port: 801
  cipher: chacha20-ietf-poly1305
- name: 🇯🇵:日本-ss-185.172.113.101:810-可用-中转:185.172.113.100-不支持Netflix
  type: ss
  server: 185.172.113.101
  password: G!yBwPWH3Vao
  port: 810
  cipher: chacha20-ietf-poly1305
- name: 🇩🇪:德国-ss-165.22.73.126:23335-可用-直连-不支持Netflix
  type: ss
  server: 165.22.73.126
  password: 7d99ae502227454ea998d71e4b62a388
  port: 23335
  cipher: aes-256-cfb
- name: 🇩🇪:德国-ss-51.38.112.84:44-可用-直连-不支持Netflix
  type: ss
  server: 51.38.112.84
  password: instgram.com/openvpnssh
  port: 44
  cipher: aes-256-cfb
- name: 🇨🇦:加拿大-ss-196.247.59.154:806-可用-直连-不支持Netflix
  type: ss
  server: 196.247.59.154
  password: G!yBwPWH3Vao
  port: 806
  cipher: chacha20-ietf-poly1305
- name: 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 31.133.100.49
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 83.229.73.60
  password: '8460400130'
  port: 50003
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 185.162.126.217
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇿🇦:南非-ss-102.130.118.99:50004-被墙-直连-解锁南非地区NF非自制剧
  type: ss
  server: 102.130.118.99
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇷🇴:罗马尼亚-ss-185.126.116.119:9079-被墙-直连-解锁瑞士地区NF非自制剧
  type: ss
  server: 185.126.116.119
  password: TPqX8edgbAURcAMb
  port: 9079
  cipher: aes-256-cfb
- name: 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇨🇳:中国-vmess-1.14.105.224:666-可用-直连-完全不支持NF
  type: vmess
  server: 1.14.105.224
  network: ws
  port: 666
  uuid: dbeb0fa0-664d-428b-9328-fcf62282635d
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇷🇴:罗马尼亚-vmess-109.166.39.183:39183-可用-直连-仅支持美国地区NF自制剧
  type: vmess
  server: 109.166.39.183
  network: ws
  port: 39183
  uuid: 184962b0-f5c6-4f7c-a766-00046269ffaa
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /tiktok
- name: 🇨🇳:中国-vmess-110.42.138.122:18080-可用-直连-完全不支持NF
  type: vmess
  server: 110.42.138.122
  network: ws
  port: 18080
  uuid: 6a9a236c-e99b-44d8-b414-bbcd6e7b1465
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-106.12.168.13:23117-可用-直连-完全不支持NF
  type: vmess
  server: 106.12.168.13
  network: ws
  port: 23117
  uuid: 6479ce34-0355-422d-d07e-d74116866fd2
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇺🇸:美国-vmess-138.2.122.102:25896-可用-直连-解锁韩国地区NF非自制剧
  type: vmess
  server: 138.2.122.102
  network: ws
  port: 25896
  uuid: 1f5db39f-9421-4835-8819-fb99d4eac4ea
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇺🇸:美国-vmess-emby.metalink.cf:36369-可用-中转:208.72.153.128-完全不支持NF
  type: vmess
  server: emby.metalink.cf
  network: ws
  port: 36369
  uuid: 859fd7c6-c76d-4e9b-fa4e-b3b057e4520e
  alterId: 4
  cipher: auto
  udp: false
  tls: true
  ws-path: /
- name: 🇨🇳:中国-vmess-47.93.231.218:53022-可用-直连-完全不支持NF
  type: vmess
  server: 47.93.231.218
  network: ws
  port: 53022
  uuid: 95fd7642-2160-4528-e909-3d526b533013
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-124.223.44.153:80-可用-直连-完全不支持NF
  type: vmess
  server: 124.223.44.153
  network: ws
  port: 80
  uuid: 8017dfd8-f239-4ec6-e2dd-416189856438
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇨🇳:中国-vmess-106.12.168.13:13156-可用-直连-完全不支持NF
  type: vmess
  server: 106.12.168.13
  network: ws
  port: 13156
  uuid: 9bf4cba4-9e9e-4da4-8e65-f7c487c539df
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /
- name: 🇷🇴:罗马尼亚-vmess-109.166.39.216:39216-可用-直连-仅支持美国地区NF自制剧
  type: vmess
  server: 109.166.39.216
  network: ws
  port: 39216
  uuid: 5022b474-6ba7-4f66-b7a1-04cc4814d2ed
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /tiktok
- name: 🇷🇴:罗马尼亚-vmess-109.166.39.205:39205-可用-直连-仅支持美国地区NF自制剧
  type: vmess
  server: 109.166.39.205
  network: ws
  port: 39205
  uuid: 548cfd27-e18f-406b-84f6-74de849e27b8
  alterId: 4
  cipher: auto
  udp: false
  tls: false
  ws-path: /tiktok

# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
proxy-groups:
  # 保留的自定义节点
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-emby.metalink.cf:36369-可用-中转:208.72.153.128-完全不支持NF
  - 🇺🇸:美国-vmess-138.2.122.102:25896-可用-直连-解锁韩国地区NF非自制剧
  - 🇺🇸:美国-ss-92.38.176.81:811-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-169.197.141.5:3306-可用-直连-不支持Netflix
  - 🇺🇸:美国-ss-134.195.196.85:5001-可用-直连-不支持Netflix
  - 🇷🇴:罗马尼亚-vmess-109.166.39.216:39216-可用-直连-仅支持美国地区NF自制剧
  - 🇷🇴:罗马尼亚-vmess-109.166.39.205:39205-可用-直连-仅支持美国地区NF自制剧
  - 🇷🇴:罗马尼亚-vmess-109.166.39.183:39183-可用-直连-仅支持美国地区NF自制剧
  - 🇯🇵:日本-ss-185.172.113.101:810-可用-中转:185.172.113.100-不支持Netflix
  - 🇩🇪:德国-ss-51.38.112.84:44-可用-直连-不支持Netflix
  - 🇩🇪:德国-ss-165.22.73.126:23335-可用-直连-不支持Netflix
  - 🇨🇳:中国-vmess-47.93.231.218:53022-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-124.223.44.153:80-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-110.42.138.122:18080-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-106.12.168.13:23117-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-106.12.168.13:13156-可用-直连-完全不支持NF
  - 🇨🇳:中国-vmess-1.14.105.224:666-可用-直连-完全不支持NF
  - 🇨🇳:中国-ss-14.29.124.168:25289-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25284-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25272-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25256-可用-直连-不支持Netflix
  - 🇨🇳:中国-ss-14.29.124.168:25251-可用-直连-不支持Netflix
  - 🇨🇦:加拿大-ss-196.247.59.154:809-可用-直连-不支持Netflix
  - 🇨🇦:加拿大-ss-196.247.59.154:806-可用-直连-不支持Netflix
  - 🇨🇦:加拿大-ss-196.247.59.154:801-可用-直连-不支持Netflix
- name: 被墙代理组
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇿🇦:南非-ss-102.130.118.99:50004-被墙-直连-解锁南非地区NF非自制剧
  - 🇷🇴:罗马尼亚-ss-185.126.116.119:9079-被墙-直连-解锁瑞士地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇮🇱:以色列-ss-185.162.126.217:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇬🇧:英国-ss-83.229.73.60:50003-被墙-直连-解锁以色列地区NF非自制剧
- name: 仅支持Netflix自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇷🇴:罗马尼亚-vmess-109.166.39.216:39216-可用-直连-仅支持美国地区NF自制剧
  - 🇷🇴:罗马尼亚-vmess-109.166.39.205:39205-可用-直连-仅支持美国地区NF自制剧
  - 🇷🇴:罗马尼亚-vmess-109.166.39.183:39183-可用-直连-仅支持美国地区NF自制剧
- name: 解锁Netflix非自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-vmess-138.2.122.102:25896-可用-直连-解锁韩国地区NF非自制剧
- name: 入口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
  - PROXY
- name: 出口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 被墙代理组
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
- name: RELAY_PROXY
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: relay
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 入口代理组
  - 出口代理组
- name: NETFLIX_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Tiktok_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Bili_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
- name: IQiyi_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY

# 黑名单模式，命中规则使用代理
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
  # > Netflix
- DOMAIN-SUFFIX,netflix.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflix.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxext.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxso.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxvideo.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest0.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest1.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest2.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest3.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest4.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest5.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest6.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest7.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest8.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest9.com,NETFLIX_PROXY
  # Netflix测速网站
- DOMAIN-SUFFIX,fast.com,NETFLIX_PROXY
  # - RULE-SET,video_netflix,NETFLIX_PROXY
  # > TikTok
- PROCESS-NAME,com.ss.android.ugc.trill,Tiktok_PROXY
- DOMAIN-SUFFIX,byteoversea.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ibytedtos.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ipstatp.com,Tiktok_PROXY
- DOMAIN-SUFFIX,muscdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,musical.ly,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktok.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tik-tokapi.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokcdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokv.com,Tiktok_PROXY
  # - RULE-SET,video_tiktok,Tiktok_PROXY
  # > iQIYI
- DOMAIN-SUFFIX,iq.com,IQiyi_PROXY
- DOMAIN,intl.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-rcd.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-subscription.iqiyi.com,IQiyi_PROXY
  # - RULE-SET,video_iqiyi,IQiyi_PROXY
  # > Bilibili
- PROCESS-NAME,com.bilibili.app.in,Bili_PROXY
- PROCESS-NAME,tv.danmaku.bili,Bili_PROXY
- DOMAIN-SUFFIX,acg.tv,Bili_PROXY
- DOMAIN-SUFFIX,acgvideo.com,Bili_PROXY
- DOMAIN-SUFFIX,b23.tv,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.com,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.net,Bili_PROXY
- DOMAIN-SUFFIX,bilibili.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.net,Bili_PROXY
- DOMAIN-SUFFIX,bilivideo.com,Bili_PROXY
- DOMAIN-SUFFIX,hdslb.com,Bili_PROXY
- DOMAIN-SUFFIX,im9.com,Bili_PROXY
- DOMAIN-SUFFIX,smtcdns.net,Bili_PROXY
  # 后面追加规则
